# This is a basic workflow that is manually triggered

name: WorkFlow Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

#setting environment variables
env:
  env_var: "test_env_var"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  test1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: step1
        run: echo "The job belongs to ${{ github.workflow}}" is manually triggered by a "${{ github.actor }} using  ${{ github.event_name }} event."
      - name: step2
        run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: step3
        run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

  test2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: test1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: step4
        run: echo "Environment variable is ${{ env.env_var }}"
      - name: step5
        run: echo "few default environment variables. os - $RUNNER_OS ,server url -  $GITHUB_SERVER_URL, run id - $GITHUB_RUN_ID"
      - name: step6
        run: echo "few more default environment variables. event name - $GITHUB_EVENT_NAME , owner - $GITHUB_REPOSITORY_OWNER"
