# This is a workflow to test Code quality of the python pacakge

name: Package Publish

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Sets up python in the runner
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Installs poerty
      - name: Install poetry
        run: |
          curl -sSL \
            "https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py" | python
          # Adding `poetry` to `$PATH`:
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
          
      # Install all the dependencies setup in poetry.toml
      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install
      
      # Publish package to Pypi
      - name: Publish Package
        run: |
          poetry publish --build --username aadarshgaikwad96 --password ${{ secrets.PYPI_TOKEN }}
